name: just_play
description: 'A music player app for playing local .mp3 files with a unique interface.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  just_audio: ^0.9.38
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  file_picker: ^8.0.6
  restart_app: ^1.2.1
  sqflite: ^2.3.3+1
  audiotags: ^1.4.0
  path: ^1.9.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
